In [3]:
import pandas as pd
import os

In [4]:
WORKDIR = '/proj/regeps/regep00/studies/TopMed/data/dna/whole_genome/TopMed/data/freezes/freeze.10.cdnm'
IMISS_FILE = 'tmp/GECOPD_annotated_plink_merged.imiss'
SEXCHECK_FILE = 'tmp/GECOPD_annotated_plink_merged.sexcheck'
MULTIOMICS_FILE = 'multiomics/GECOPD/ANNOTATED_MANIFEST.csv'
HET_FILE = 'tmp/GECOPD_annotated_plink_merged.het'
C_DATA_FILE = 'multiomics/GECOPD/c_data.build_sample_groups'

In [5]:
os.chdir(WORKDIR)

In [6]:
het = pd.read_csv(HET_FILE, delim_whitespace=True, usecols=['IID', 'F'])
het

             IID         F
0      NWD100095 -0.003114
1      NWD100295  0.008409
2      NWD100327 -0.004979
3      NWD100517  0.003173
4      NWD100651  0.005658
...          ...       ...
10748  NWD999796  0.015610
10749  NWD999840  0.016140
10750  NWD999849  0.009068
10751  NWD999930  0.009083
10752  NWD999969  0.015470

[10753 rows x 2 columns]

In [7]:
imiss = pd.read_csv(IMISS_FILE, delim_whitespace=True, usecols=['IID', 'F_MISS'])
imiss

             IID    F_MISS
0      NWD100018  0.002713
1      NWD100059  0.000001
2      NWD100095  0.000019
3      NWD100109  0.000002
4      NWD100230  0.000010
...          ...       ...
10748  NWD999840  0.000007
10749  NWD999849  0.000010
10750  NWD999930  0.000009
10751  NWD999969  0.000031
10752  NWD999984  0.000789

[10753 rows x 2 columns]

In [8]:
sexcheck = pd.read_csv(SEXCHECK_FILE, delim_whitespace=True, usecols=['IID', 'SNPSEX', 'F'])
sexcheck = sexcheck.rename(columns={'F': 'XHomFStat'})
sexcheck

             IID  SNPSEX  XHomFStat
0      NWD100095       2   0.041640
1      NWD100295       1   1.000000
2      NWD100327       2  -0.004391
3      NWD100517       1   1.000000
4      NWD100651       2  -0.026660
...          ...     ...        ...
10748  NWD999796       1   1.000000
10749  NWD999840       1   1.000000
10750  NWD999849       2   0.121500
10751  NWD999930       2  -0.021190
10752  NWD999969       2   0.072260

[10753 rows x 3 columns]

In [9]:
multiomics = pd.read_csv(MULTIOMICS_FILE)
multiomics = multiomics.merge(het, left_on='SampleAlias', right_on='IID', how='left')
multiomics = multiomics.merge(imiss, left_on='SampleAlias', right_on='IID', how='left')
multiomics = multiomics.merge(sexcheck, left_on='SampleAlias', right_on='IID', how='left')
multiomics

/udd/rejpz/.conda/envs/cdnm-jupyter-python-3.7.6/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (3,10,11,12,14,15,16,18,19,20,24,25,26,30,31,33,34,37,38,39,42,46,51,53,57,58,59,60,61,62,63,64,71,72,74,77,78,79,80,81,82,84,92) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
0,0,0,NWD100018,NaN,NWD100018,w,0,0,ST-01000557,S-001174464,...,NaN,NaN,NaN,NWD100018,0.015770,NWD100018,0.002713,NWD100018,1.0,1.00000
1,1,1,NWD100059,NaN,NWD100059,w,0,0,ST-00033813,S-000554104,...,NaN,NaN,reassign,NWD100059,0.010860,NWD100059,0.000001,NWD100059,2.0,0.03821
2,2,2,NWD100095,NaN,NWD100095,w,0,0,ST-00075744,S-000964706,...,NaN,NaN,NaN,NWD100095,-0.003114,NWD100095,0.000019,NWD100095,2.0,0.04164
3,3,3,NWD100109,NaN,NWD100109,w,0,0,ST-00078957,S-001558939,...,NaN,NaN,NaN,NWD100109,0.001576,NWD100109,0.000002,NWD100109,2.0,0.01363
4,4,4,NWD100230,NaN,NWD100230,w,0,0,ST-00077474,S-001557255,...,NaN,NaN,NaN,NWD100230,0.002402,NWD100230,0.000010,NWD100230,2.0,0.02348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37574,37574,37574,S-001644042_accepted_hits.sorted.bam,S-001644042,S-001644042_accepted_hits.sorted.bam,r,4,0,ST-01024867,S-001644042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37575,37575,37575,S-001644043_accepted_hits.sorted.bam,S-001644043,S-001644043_accepted_hits.sorted.bam,r,4,0,ST-01024865,S-001644043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37576,37576,37576,S-001644044_accepted_hits.sorted.bam,S-001644044,S-001644044_accepted_hits.sorted.bam,r,4,0,ST-01024872,S-001644044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37577,37577,37577,S-001648029_CGGCGTGA-GCGCCTGT_L003_accepted_hi...,S-001648029,S-001648029_CGGCGTGA-GCGCCTGT_L003_accepted_hi...,r,4,0,ST-01002733,S-001648029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37578,37578,37578,S-001648324_CTCTCGTC-TATAACCT_L002_accepted_hi...,S-001648324,S-001648324_CTCTCGTC-TATAACCT_L002_accepted_hi...,r,4,0,ST-01007272,S-001648324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
wgs_samples = multiomics[multiomics['dataset_id'] == 0]
wgs_samples

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
0,0,0,NWD100018,NaN,NWD100018,w,0,0,ST-01000557,S-001174464,...,NaN,NaN,NaN,NWD100018,0.015770,NWD100018,0.002713,NWD100018,1.0,1.00000
1,1,1,NWD100059,NaN,NWD100059,w,0,0,ST-00033813,S-000554104,...,NaN,NaN,reassign,NWD100059,0.010860,NWD100059,0.000001,NWD100059,2.0,0.03821
2,2,2,NWD100095,NaN,NWD100095,w,0,0,ST-00075744,S-000964706,...,NaN,NaN,NaN,NWD100095,-0.003114,NWD100095,0.000019,NWD100095,2.0,0.04164
3,3,3,NWD100109,NaN,NWD100109,w,0,0,ST-00078957,S-001558939,...,NaN,NaN,NaN,NWD100109,0.001576,NWD100109,0.000002,NWD100109,2.0,0.01363
4,4,4,NWD100230,NaN,NWD100230,w,0,0,ST-00077474,S-001557255,...,NaN,NaN,NaN,NWD100230,0.002402,NWD100230,0.000010,NWD100230,2.0,0.02348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10721,10721,10721,NWD999840,NaN,NWD999840,w,0,0,ST-01003339,S-001151679,...,NaN,NaN,NaN,NWD999840,0.016140,NWD999840,0.000007,NWD999840,1.0,1.00000
10722,10722,10722,NWD999849,NaN,NWD999849,w,0,0,ST-00007577,S-001116669,...,NaN,NaN,NaN,NWD999849,0.009068,NWD999849,0.000010,NWD999849,2.0,0.12150
10723,10723,10723,NWD999930,NaN,NWD999930,w,0,0,ST-00078863,S-001174118,...,NaN,NaN,NaN,NWD999930,0.009083,NWD999930,0.000009,NWD999930,2.0,-0.02119
10724,10724,10724,NWD999969,NaN,NWD999969,w,0,0,ST-00078944,S-000969098,...,NaN,NaN,NaN,NWD999969,0.015470,NWD999969,0.000031,NWD999969,2.0,0.07226
10725,10725,10725,NWD999984,NaN,NWD999984,w,0,0,ST-00077856,S-001128429,...,NaN,NaN,NaN,NWD999984,-0.003092,NWD999984,0.000789,NWD999984,1.0,1.00000

In [11]:
wgs_samples[(wgs_samples['F'] > 0.2) | (wgs_samples['F'] < -0.2)]

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
15,15,15,NWD100991,NaN,NWD100991,w,0,0,ST-00075884,S-001151541,...,NaN,NaN,reassign,NWD100991,0.2531,NWD100991,0.000005,NWD100991,0.0,0.4416
51,51,51,NWD103568,NaN,NWD103568,w,0,0,ST-01016208,S-001625611,...,NaN,NaN,NaN,NWD103568,-0.3169,NWD103568,0.000271,NWD103568,1.0,1.0000
153,153,153,NWD112319,NaN,NWD112319,w,0,0,ST-01016451,S-001625978,...,NaN,NaN,NaN,NWD112319,-0.3068,NWD112319,0.003739,NWD112319,2.0,-0.6010
267,267,267,NWD120949,NaN,NWD120949,w,0,0,ST-01016125,S-001626046,...,NaN,NaN,NaN,NWD120949,-0.3211,NWD120949,0.000030,NWD120949,1.0,1.0000
317,317,317,NWD124790,NaN,NWD124790,w,0,0,ST-01024088,S-001603790,...,NaN,NaN,NaN,NWD124790,-0.3176,NWD124790,0.000083,NWD124790,2.0,-0.6749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10301,10301,10301,NWD963332,NaN,NWD963332,w,0,0,ST-01016207,S-001624991,...,NaN,NaN,NaN,NWD963332,-0.3252,NWD963332,0.000024,NWD963332,1.0,1.0000
10319,10319,10319,NWD965569,NaN,NWD965569,w,0,0,ST-01015853,S-001625985,...,NaN,NaN,NaN,NWD965569,-0.3146,NWD965569,0.000796,NWD965569,2.0,-0.5623
10354,10354,10354,NWD968397,NaN,NWD968397,w,0,0,ST-01025230,S-001603865,...,NaN,NaN,NaN,NWD968397,-0.3131,NWD968397,0.000026,NWD968397,1.0,1.0000
10494,10494,10494,NWD979617,NaN,NWD979617,w,0,0,ST-00032597,S-000965557,...,NaN,NaN,NaN,NWD979617,0.2534,NWD979617,0.000092,NWD979617,0.0,0.7550
10514,10514,10514,NWD981356,NaN,NWD981356,w,0,0,ST-01024102,S-001603877,...,NaN,NaN,NaN,NWD981356,-0.3207,NWD981356,0.000019,NWD981356,2.0,-0.6512

In [12]:
wgs_samples[(wgs_samples['SNPSEX'] == 0)]

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
15,15,15,NWD100991,NaN,NWD100991,w,0,0,ST-00075884,S-001151541,...,NaN,NaN,reassign,NWD100991,0.253100,NWD100991,0.000005,NWD100991,0.0,0.4416
598,598,598,NWD148867,NaN,NWD148867,w,0,0,ST-00074864,S-000965629,...,NaN,NaN,NaN,NWD148867,0.022100,NWD148867,0.000028,NWD148867,0.0,0.2394
752,752,752,NWD162548,NaN,NWD162548,w,0,0,ST-01007304,S-001151880,...,NaN,NaN,NaN,NWD162548,0.038450,NWD162548,0.000007,NWD162548,0.0,0.2152
916,916,916,NWD244480,NaN,NWD244480,w,0,0,ST-00037682,S-000561648,...,NaN,drop,NaN,NWD244480,0.247300,NWD244480,0.000006,NWD244480,0.0,0.4746
1184,1184,1184,NWD195752,NaN,NWD195752,w,0,0,ST-00075792,S-001516290,...,NaN,NaN,NaN,NWD195752,0.099570,NWD195752,0.000073,NWD195752,0.0,0.7980
1185,1185,1185,NWD615719,NaN,NWD615719,w,0,0,ST-00075792,S-001611902,...,NaN,NaN,NaN,NWD615719,0.099590,NWD615719,0.000060,NWD615719,0.0,0.7980
1186,1186,1186,NWD895371,NaN,NWD895371,w,0,0,ST-00075792,S-000966079,...,NaN,NaN,NaN,NWD895371,0.099510,NWD895371,0.000057,NWD895371,0.0,0.7981
1216,1216,1216,NWD198650,NaN,NWD198650,w,0,0,ST-00078884,S-001558148,...,NaN,NaN,NaN,NWD198650,0.009213,NWD198650,0.000006,NWD198650,0.0,0.2198
1809,1809,1809,NWD245633,NaN,NWD245633,w,0,0,ST-00075036,S-000966752,...,NaN,NaN,NaN,NWD245633,0.108300,NWD245633,0.000012,NWD245633,0.0,0.2247
2073,2073,2073,NWD267258,NaN,NWD267258,w,0,0,ST-00076094,S-001151897,...,NaN,drop,drop,NWD267258,0.233100,NWD267258,0.000014,NWD267258,0.0,0.3740
2634,2634,2634,NWD314163,NaN,NWD314163,w,0,0,ST-00077631,S-001152176,...,NaN,NaN,NaN,NWD314163,-0.001930,NWD314163,0.000010,NWD314163,0.0,0.6339
2893,2893,2893,NWD337191,NaN,NWD337191,w,0,0,ST-00076745,S-001559173,...,NaN,NaN,NaN,NWD337191,0.026880,NWD337191,0.000009,NWD337191,0.0,0.2793
4480,4480,4480,NWD468904,NaN,NWD468904,w,0,0,ST-00078366,S-000964469,...,NaN,NaN,NaN,NWD468904,0.082340,NWD468904,0.000741,NWD468904,0.0,0.3137
5005,5005,5005,NWD511638,NaN,NWD511638,w,0,0,ST-00075889,S-001557525,...,NaN,NaN,NaN,NWD511638,0.052320,NWD511638,0.000009,NWD511638,0.0,0.2291
5244,5244,5244,NWD777192,NaN,NWD777192,w,0,0,ST-00037131,S-000524855,...,NaN,NaN,NaN,NWD777192,0.246200,NWD777192,0.000014,NWD777192,0.0,0.3405
6169,6169,6169,NWD608153,NaN,NWD608153,w,0,0,ST-01005263,S-001152178,...,NaN,NaN,NaN,NWD608153,0.016780,NWD608153,0.000035,NWD608153,0.0,0.3826
7248,7248,7248,NWD702694,NaN,NWD702694,w,0,0,ST-00075772,S-001561457,...,NaN,NaN,NaN,NWD702694,0.046180,NWD702694,0.000045,NWD702694,0.0,0.4179
7630,7630,7630,NWD733400,NaN,NWD733400,w,0,0,ST-00008656,S-001558584,...,NaN,NaN,NaN,NWD733400,-0.000726,NWD733400,0.000039,NWD733400,0.0,0.2035
7870,7870,7870,NWD752879,NaN,NWD752879,w,0,0,ST-01006942,S-001059082,...,NaN,NaN,NaN,NWD752879,0.003393,NWD752879,0.000023,NWD752879,0.0,0.2445
8767,8767,8767,NWD829243,NaN,NWD829243,w,0,0,ST-00079219,S-001557836,...,NaN,NaN,NaN,NWD829243,-0.001082,NWD829243,0.000017,NWD829243,0.0,0.2260
8809,8809,8809,NWD832815,NaN,NWD832815,w,0,0,ST-00074317,S-000962808,...,NaN,NaN,NaN,NWD832815,0.268100,NWD832815,0.000082,NWD832815,0.0,0.7320
9093,9093,9093,NWD858702,NaN,NWD858702,w,0,0,ST-01007063,S-001559839,...,NaN,NaN,NaN,NWD858702,-0.005074,NWD858702,0.000033,NWD858702,0.0,0.2072
10250,10250,10250,NWD958907,NaN,NWD958907,w,0,0,ST-01001882,S-001559421,...,NaN,NaN,NaN,NWD958907,0.056400,NWD958907,0.000008,NWD958907,0.0,0.2447
10494,10494,10494,NWD979617,NaN,NWD979617,w,0,0,ST-00032597,S-000965557,...,NaN,NaN,NaN,NWD979617,0.253400,NWD979617,0.000092,NWD979617,0.0,0.7550

In [13]:
wgs_samples[(wgs_samples['ExpectedGender'] == 1) & (wgs_samples['XHomFStat'] < 0.8)]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, SampleLabel, S_SAMPLEID_manifest, SampleAlias, SampleTypeCode, dataset_id, is_reference, S_SUBJECTID, S_SAMPLEID, S_SUBJECTID_sample, S_STUDYID, ALIASTYPE, ALIASID, s_sampleid, sampledesc, sampletypeid_x, batchid, samplefamilyid, activeflag_x, s_samplefamilyid, samplefamilydesc, initialpackageid, initialdepartmentid, sstudyid, studysiteid, collectiondt, collectmethodid, verifiedby, verifieddt, approvedby, approveddt, recieveddt, cocflag, restrictionsflag, age, ageunits, restrictclassid, subjectid, externalsubject, animal, diseaseid, tissueid, metastasisid, clinicaldiagid, conditionalapprovalreason, conditionalapprovalflag, clinicalevent, initialmass, initialmassunits, initialvolume, initialvolumeunits, deviationdesc, notes, auditsequence, tracelogid, usersequence, templateflag, createdt, createby, createtool, moddt, modby, modtool, participantid, participanteventid, kittrackitem, clinicalprotocolid, clinicalprotocolversionid, clinicalprotocolrevision, eventdefid, activeflag_y, sampletypeid_y, specimendefid, u_collectionid, u_visitname, u_timepointname, u_initsampletypeid, u_inittreatmenttypeid, u_initcontainertypeid, u_initenvironmentid, u_specimentypeid, u_collectiontypid, u_legacyfamilyid, u_packageid, ExpectedGender, ObservedGender, flags, group_id, c_group, action_overridden, status, action_overridden.1, action, IID_x, F, IID_y, F_MISS, IID, SNPSEX, ...]
Index: []

[0 rows x 101 columns]

In [14]:
wgs_samples[(wgs_samples['ExpectedGender'] == 2) & (wgs_samples['XHomFStat'] > 0.2)]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, SampleLabel, S_SAMPLEID_manifest, SampleAlias, SampleTypeCode, dataset_id, is_reference, S_SUBJECTID, S_SAMPLEID, S_SUBJECTID_sample, S_STUDYID, ALIASTYPE, ALIASID, s_sampleid, sampledesc, sampletypeid_x, batchid, samplefamilyid, activeflag_x, s_samplefamilyid, samplefamilydesc, initialpackageid, initialdepartmentid, sstudyid, studysiteid, collectiondt, collectmethodid, verifiedby, verifieddt, approvedby, approveddt, recieveddt, cocflag, restrictionsflag, age, ageunits, restrictclassid, subjectid, externalsubject, animal, diseaseid, tissueid, metastasisid, clinicaldiagid, conditionalapprovalreason, conditionalapprovalflag, clinicalevent, initialmass, initialmassunits, initialvolume, initialvolumeunits, deviationdesc, notes, auditsequence, tracelogid, usersequence, templateflag, createdt, createby, createtool, moddt, modby, modtool, participantid, participanteventid, kittrackitem, clinicalprotocolid, clinicalprotocolversionid, clinicalprotocolrevision, eventdefid, activeflag_y, sampletypeid_y, specimendefid, u_collectionid, u_visitname, u_timepointname, u_initsampletypeid, u_inittreatmenttypeid, u_initcontainertypeid, u_initenvironmentid, u_specimentypeid, u_collectiontypid, u_legacyfamilyid, u_packageid, ExpectedGender, ObservedGender, flags, group_id, c_group, action_overridden, status, action_overridden.1, action, IID_x, F, IID_y, F_MISS, IID, SNPSEX, ...]
Index: []

[0 rows x 101 columns]

In [15]:
wgs_samples[(wgs_samples['F_MISS'] > 0.1)]

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
202,202,202,NWD115821,NaN,NWD115821,w,0,0,ST-01024895,S-001627251,...,NaN,NaN,NaN,NWD115821,0.017480,NWD115821,0.1213,NWD115821,1.0,1.000000
242,242,242,NWD256937,NaN,NWD256937,w,0,0,ST-00033679,S-000954727,...,NaN,NaN,NaN,NWD256937,0.029920,NWD256937,0.1636,NWD256937,1.0,1.000000
966,966,966,NWD178870,NaN,NWD178870,w,0,0,ST-01023645,S-001627255,...,NaN,NaN,NaN,NWD178870,-0.013500,NWD178870,0.1170,NWD178870,1.0,1.000000
1608,1608,1608,NWD782097,NaN,NWD782097,w,0,0,ST-01003162,S-001099086,...,NaN,NaN,NaN,NWD782097,0.022170,NWD782097,0.2207,NWD782097,2.0,-0.082600
1644,1644,1644,NWD233061,NaN,NWD233061,w,0,0,ST-01004971,S-001099084,...,NaN,NaN,NaN,NWD233061,0.019930,NWD233061,0.1887,NWD233061,1.0,1.000000
1658,1658,1658,NWD233813,NaN,NWD233813,w,0,0,ST-01001399,S-001099059,...,NaN,NaN,NaN,NWD233813,-0.005310,NWD233813,0.2751,NWD233813,1.0,1.000000
2040,2040,2040,NWD264599,NaN,NWD264599,w,0,0,ST-01001423,S-001627434,...,NaN,NaN,NaN,NWD264599,0.026290,NWD264599,0.2459,NWD264599,1.0,1.000000
2164,2164,2164,NWD787816,NaN,NWD787816,w,0,0,ST-01002278,S-001147233,...,NaN,NaN,NaN,NWD787816,0.021110,NWD787816,0.1305,NWD787816,1.0,1.000000
2493,2493,2493,NWD302608,NaN,NWD302608,w,0,0,ST-00030561,S-000954721,...,NaN,NaN,NaN,NWD302608,0.018920,NWD302608,0.1721,NWD302608,1.0,1.000000
2678,2678,2678,NWD318063,NaN,NWD318063,w,0,0,ST-01002219,S-001147230,...,NaN,NaN,NaN,NWD318063,0.020760,NWD318063,0.1019,NWD318063,2.0,0.019480
2931,2931,2931,NWD340221,NaN,NWD340221,w,0,0,ST-00078717,S-001627432,...,NaN,NaN,NaN,NWD340221,0.016670,NWD340221,0.1694,NWD340221,2.0,0.090390
2962,2962,2962,NWD342887,NaN,NWD342887,w,0,0,ST-00074661,S-001627431,...,NaN,NaN,NaN,NWD342887,0.025730,NWD342887,0.2797,NWD342887,1.0,1.000000
3523,3523,3523,NWD737719,NaN,NWD737719,w,0,0,ST-00035273,S-000537119,...,NaN,NaN,NaN,NWD737719,0.012790,NWD737719,0.2110,NWD737719,2.0,-0.017780
4101,4101,4101,NWD439315,NaN,NWD439315,w,0,0,ST-01002279,S-001147224,...,NaN,NaN,NaN,NWD439315,0.017340,NWD439315,0.1623,NWD439315,1.0,1.000000
4529,4529,4529,NWD473969,NaN,NWD473969,w,0,0,ST-01002298,S-001147238,...,NaN,NaN,NaN,NWD473969,0.014140,NWD473969,0.2167,NWD473969,1.0,1.000000
4685,4685,4685,NWD710260,NaN,NWD710260,w,0,0,ST-00079014,S-001099042,...,NaN,NaN,NaN,NWD710260,0.003364,NWD710260,0.1054,NWD710260,2.0,0.027970
5419,5419,5419,NWD997869,NaN,NWD997869,w,0,0,ST-01005391,S-001099088,...,NaN,NaN,NaN,NWD997869,-0.009229,NWD997869,0.1096,NWD997869,1.0,1.000000
6652,6652,6652,NWD649815,NaN,NWD649815,w,0,0,ST-01024575,S-001627252,...,NaN,NaN,NaN,NWD649815,0.021140,NWD649815,0.1600,NWD649815,2.0,0.036350
7356,7356,7356,NWD710364,NaN,NWD710364,w,0,0,ST-01002300,S-001147211,...,NaN,NaN,NaN,NWD710364,0.016650,NWD710364,0.2775,NWD710364,1.0,1.000000
7919,7919,7919,NWD756865,NaN,NWD756865,w,0,0,ST-01002590,S-001627438,...,NaN,NaN,NaN,NWD756865,0.017810,NWD756865,0.1504,NWD756865,1.0,1.000000
7927,7927,7927,NWD758047,NaN,NWD758047,w,0,0,ST-01002176,S-001147242,...,NaN,NaN,NaN,NWD758047,0.006079,NWD758047,0.1169,NWD758047,2.0,-0.007224
7940,7940,7940,NWD759278,NaN,NWD759278,w,0,0,ST-00033715,S-000956049,...,NaN,NaN,NaN,NWD759278,0.002932,NWD759278,0.1819,NWD759278,1.0,1.000000
8011,8011,8011,NWD856675,NaN,NWD856675,w,0,0,ST-00033459,S-000947752,...,NaN,NaN,NaN,NWD856675,-0.003830,NWD856675,0.1227,NWD856675,2.0,-0.019110
8713,8713,8713,NWD824277,NaN,NWD824277,w,0,0,ST-00038086,S-001627259,...,NaN,NaN,NaN,NWD824277,0.001739,NWD824277,0.1683,NWD824277,1.0,1.000000

In [16]:
wgs_samples['fail_heterozygosity'] = (wgs_samples['F'] > 0.2) | (wgs_samples['F'] < -0.2)
wgs_samples['fail_sexcheck'] = wgs_samples['SNPSEX'] == 0
wgs_samples['fail_missing'] = wgs_samples['F_MISS'] > 0.1
wgs_samples

/d/tmp/rejpz/ipykernel_24113/3421678645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wgs_samples['fail_heterozygosity'] = (wgs_samples['F'] > 0.2) | (wgs_samples['F'] < -0.2)
/d/tmp/rejpz/ipykernel_24113/3421678645.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wgs_samples['fail_sexcheck'] = wgs_samples['SNPSEX'] == 0
/d/tmp/rejpz/ipykernel_24113/3421678645.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wgs_samples['fail_missing'] = wgs_samples['F_MISS'] > 0.1

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat,fail_heterozygosity,fail_sexcheck,fail_missing
0,0,0,NWD100018,NaN,NWD100018,w,0,0,ST-01000557,S-001174464,...,NWD100018,0.015770,NWD100018,0.002713,NWD100018,1.0,1.00000,False,False,False
1,1,1,NWD100059,NaN,NWD100059,w,0,0,ST-00033813,S-000554104,...,NWD100059,0.010860,NWD100059,0.000001,NWD100059,2.0,0.03821,False,False,False
2,2,2,NWD100095,NaN,NWD100095,w,0,0,ST-00075744,S-000964706,...,NWD100095,-0.003114,NWD100095,0.000019,NWD100095,2.0,0.04164,False,False,False
3,3,3,NWD100109,NaN,NWD100109,w,0,0,ST-00078957,S-001558939,...,NWD100109,0.001576,NWD100109,0.000002,NWD100109,2.0,0.01363,False,False,False
4,4,4,NWD100230,NaN,NWD100230,w,0,0,ST-00077474,S-001557255,...,NWD100230,0.002402,NWD100230,0.000010,NWD100230,2.0,0.02348,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10721,10721,10721,NWD999840,NaN,NWD999840,w,0,0,ST-01003339,S-001151679,...,NWD999840,0.016140,NWD999840,0.000007,NWD999840,1.0,1.00000,False,False,False
10722,10722,10722,NWD999849,NaN,NWD999849,w,0,0,ST-00007577,S-001116669,...,NWD999849,0.009068,NWD999849,0.000010,NWD999849,2.0,0.12150,False,False,False
10723,10723,10723,NWD999930,NaN,NWD999930,w,0,0,ST-00078863,S-001174118,...,NWD999930,0.009083,NWD999930,0.000009,NWD999930,2.0,-0.02119,False,False,False
10724,10724,10724,NWD999969,NaN,NWD999969,w,0,0,ST-00078944,S-000969098,...,NWD999969,0.015470,NWD999969,0.000031,NWD999969,2.0,0.07226,False,False,False
10725,10725,10725,NWD999984,NaN,NWD999984,w,0,0,ST-00077856,S-001128429,...,NWD999984,-0.003092,NWD999984,0.000789,NWD999984,1.0,1.00000,False,False,False

In [17]:
flagged = wgs_samples[(wgs_samples['fail_sexcheck'] == True) | (wgs_samples['fail_heterozygosity'] == True) | (wgs_samples['fail_missing'] == True)]
flagged[['SampleAlias', 'fail_heterozygosity', 'F', 'fail_sexcheck', 'XHomFStat', 'fail_missing', 'F_MISS', 'flags', 'action']]
flagged.to_csv('multiomics/GECOPD/flagged_samples.csv')

# Table 3: Samples involved with Plate 103

In [18]:
PLATE_MANIFESTS = [
    'plate103/PL-01007365_v2.csv',
    'plate103/PL-01007396_v2.csv',
    'plate103/PL-01007962_v2.csv',
]

In [19]:
p0 = pd.read_csv(PLATE_MANIFESTS[0])
p1 = pd.read_csv(PLATE_MANIFESTS[1])
p2 = pd.read_csv(PLATE_MANIFESTS[2])
plate_manifests = pd.concat([p0, p1, p2])
plate_manifests

,ROW,COL,SUBJECTID,SAMPLEID,ALIASES
0,A,1,ST-00035127,S-000553917,NWD570756 ...
1,A,10,ST-00073935,S-001110949,NWD928094 ...
2,A,11,ST-01005121,S-001036386,NWD414052|NWD506449|TOE304395 ...
3,A,12,ST-00073296,S-000953391,NWD861833 ...
4,A,2,ST-00036057,S-000533475,NWD794175 ...
...,...,...,...,...,...
89,H,5,ST-00073553,S-001110916,NWD622936|NWD937800|TOE225664 ...
90,H,6,ST-00040951,S-000537550,NWD213055|NWD824657|TOE980969 ...
91,H,7,ST-00038104,S-000537183,NWD281018 ...
92,H,8,ST-01005316,S-001152072,NWD108023|NWD733322|TOE672588 ...
93,H,9,ST-01002480,S-001173914,NWD215983|NWD867190|TOE959331 ...

In [20]:
plate_103_samples = plate_manifests.SAMPLEID.to_frame().drop_duplicates()
plate_103_samples = plate_103_samples.merge(multiomics, left_on='SAMPLEID', right_on='S_SAMPLEID')
plate_103_samples.sort_values(['group_id'], inplace=True)
plate_103_samples.to_csv('multiomics/GECOPD/plate_103_samples.csv', index=False, columns=[
    'SampleAlias', 'S_SUBJECTID', 'flags', 'action', 'group_id', 'F', 'F_MISS', 'SNPSEX', 'XHomFStat',
])
plate_103_samples

,SAMPLEID,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
301,S-001116430,26704,26704,TOE171917_203693970018_R03C01_346336,S-001116430,TOE171917,m,2,0,ST-00007435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,S-000562035,1518,1518,NWD856186,NaN,NWD856186,w,0,0,ST-00039640,...,NaN,drop,drop,NWD856186,0.019280,NWD856186,0.000076,NWD856186,2.0,0.04792
325,S-000562036,26765,26765,TOE559878_203867050074_R02C01_363996,S-000562036,TOE559878,m,2,0,ST-00039640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,S-000562036,1517,1517,NWD223239,NaN,NWD223239,w,0,0,ST-00039640,...,NaN,NaN,NaN,NWD223239,0.001284,NWD223239,0.000015,NWD223239,1.0,1.00000
299,S-001116430,3360,3360,NWD375367,NaN,NWD375367,w,0,0,ST-00007435,...,NaN,NaN,NaN,NWD375367,0.019350,NWD375367,0.000087,NWD375367,2.0,0.04797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,S-001151648,29857,29857,TOE472156_203724130047_R08C01_346116,S-001151648,TOE472156,m,2,0,ST-01007244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,S-001151650,4959,4959,NWD507792,NaN,NWD507792,w,0,0,ST-01007606,...,NaN,NaN,NaN,NWD507792,-0.000427,NWD507792,0.000039,NWD507792,1.0,1.00000
184,S-001151650,25869,25869,TOE883507_204297420102_R08C01_428863,S-001151650,TOE883507,m,2,0,ST-01007606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,S-001151664,27882,27882,TOE796387_204076520173_R08C01_378969,S-001151664,TOE796387,m,2,0,ST-01007796,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,S-001151664,4657,4657,NWD483032,NaN,NWD483032,w,0,0,ST-01007796,...,NaN,NaN,NaN,NWD483032,0.010720,NWD483032,0.000066,NWD483032,2.0,0.11040

# Samples involved with Missing RNA Data

In [21]:
missing_rna_data = multiomics[multiomics['dataset_id'] == 4]
missing_rna_data

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
33594,33594,33594,S-001177272_TCCGCGAA-GTACTGAC_L005_accepted_hi...,S-001177272,S-001177272_TCCGCGAA-GTACTGAC_L005_accepted_hi...,r,4,0,ST-00076410,S-001177272,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33595,33595,33595,S-001177736_AGCGATAG-GTACTGAC_L008_accepted_hi...,S-001177736,S-001177736_AGCGATAG-GTACTGAC_L008_accepted_hi...,r,4,0,ST-01003309,S-001177736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33596,33596,33596,S-001178531_TCTCGCGC-TATAGCCT_L006_accepted_hi...,S-001178531,S-001178531_TCTCGCGC-TATAGCCT_L006_accepted_hi...,r,4,0,ST-00034432,S-001178531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33597,33597,33597,S-001178538_ATTACTCG-AGGCGAAG_L004_accepted_hi...,S-001178538,S-001178538_ATTACTCG-AGGCGAAG_L004_accepted_hi...,r,4,0,ST-00007689,S-001178538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33598,33598,33598,S-001178548_TCTCGCGC-ATAGAGGC_L006_accepted_hi...,S-001178548,S-001178548_TCTCGCGC-ATAGAGGC_L006_accepted_hi...,r,4,0,ST-00078794,S-001178548,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37574,37574,37574,S-001644042_accepted_hits.sorted.bam,S-001644042,S-001644042_accepted_hits.sorted.bam,r,4,0,ST-01024867,S-001644042,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37575,37575,37575,S-001644043_accepted_hits.sorted.bam,S-001644043,S-001644043_accepted_hits.sorted.bam,r,4,0,ST-01024865,S-001644043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37576,37576,37576,S-001644044_accepted_hits.sorted.bam,S-001644044,S-001644044_accepted_hits.sorted.bam,r,4,0,ST-01024872,S-001644044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37577,37577,37577,S-001648029_CGGCGTGA-GCGCCTGT_L003_accepted_hi...,S-001648029,S-001648029_CGGCGTGA-GCGCCTGT_L003_accepted_hi...,r,4,0,ST-01002733,S-001648029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37578,37578,37578,S-001648324_CTCTCGTC-TATAACCT_L002_accepted_hi...,S-001648324,S-001648324_CTCTCGTC-TATAACCT_L002_accepted_hi...,r,4,0,ST-01007272,S-001648324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
missing_rna_data['flags'].fillna('', inplace=True)
missing_rna_data = missing_rna_data[missing_rna_data['flags'].str.contains('unexpected_geno_nomatch')]
missing_rna_data.to_csv('multiomics/GECOPD/missing_rna_data.csv')
missing_rna_data

/udd/rejpz/.conda/envs/cdnm-jupyter-python-3.7.6/lib/python3.9/site-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
33594,33594,33594,S-001177272_TCCGCGAA-GTACTGAC_L005_accepted_hi...,S-001177272,S-001177272_TCCGCGAA-GTACTGAC_L005_accepted_hi...,r,4,0,ST-00076410,S-001177272,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33596,33596,33596,S-001178531_TCTCGCGC-TATAGCCT_L006_accepted_hi...,S-001178531,S-001178531_TCTCGCGC-TATAGCCT_L006_accepted_hi...,r,4,0,ST-00034432,S-001178531,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33597,33597,33597,S-001178538_ATTACTCG-AGGCGAAG_L004_accepted_hi...,S-001178538,S-001178538_ATTACTCG-AGGCGAAG_L004_accepted_hi...,r,4,0,ST-00007689,S-001178538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33598,33598,33598,S-001178548_TCTCGCGC-ATAGAGGC_L006_accepted_hi...,S-001178548,S-001178548_TCTCGCGC-ATAGAGGC_L006_accepted_hi...,r,4,0,ST-00078794,S-001178548,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33599,33599,33599,S-001178707_TCTCGCGC-CCTATCCT_L006_accepted_hi...,S-001178707,S-001178707_TCTCGCGC-CCTATCCT_L006_accepted_hi...,r,4,0,ST-00032869,S-001178707,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37212,37212,37212,S-001630862_accepted_hits.sorted.bam,S-001630862,S-001630862_accepted_hits.sorted.bam,r,4,0,ST-01025467,S-001630862,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37223,37223,37223,S-001632978_accepted_hits.sorted.bam,S-001632978,S-001632978_accepted_hits.sorted.bam,r,4,0,ST-01007218,S-001632978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37224,37224,37224,S-001633319_accepted_hits.sorted.bam,S-001633319,S-001633319_accepted_hits.sorted.bam,r,4,0,ST-00079436,S-001633319,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37248,37248,37248,S-001636133_accepted_hits.sorted.bam,S-001636133,S-001636133_accepted_hits.sorted.bam,r,4,0,ST-00076902,S-001636133,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37263,37263,37263,S-001636291_accepted_hits.sorted.bam,S-001636291,S-001636291_accepted_hits.sorted.bam,r,4,0,ST-01025778,S-001636291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
c_data = pd.read_csv(C_DATA_FILE)
c_data

,Unnamed: 0,ID1,ID2,attempted,expected,observed,Concord
0,0,NWD213653,10009Y,1,1,1,1.00000
1,1,10009Y,NWD213653,1,1,1,1.00000
2,2,NWD549799,10010J,1,1,1,0.99985
3,3,NWD549799,TOE187020_203833040079_R01C01_358713,1,1,1,1.00000
4,4,NWD549799,TOE199514_203824910072_R08C01_358712,1,1,1,1.00000
...,...,...,...,...,...,...,...
158031,158031,TOE590046_203991530017_R06C01_376151,S-001613494_accepted_hits.sorted.bam,0,1,0,NaN
158032,158032,S-001613494_accepted_hits.sorted.bam,NWD993624,1,0,1,0.24040
158033,158033,S-001613494_accepted_hits.sorted.bam,17694W,0,1,0,NaN
158034,158034,S-001613494_accepted_hits.sorted.bam,TOE137422_203991530017_R05C01_376150,0,1,0,NaN
158035,158035,S-001613494_accepted_hits.sorted.bam,TOE590046_203991530017_R06C01_376151,0,1,0,NaN

In [28]:
rna_wgs_missing_matches = c_data[(c_data['ID1'].str.startswith('S-')) & (c_data['ID2'].str.startswith('NWD'))]
rna_wgs_missing_matches = rna_wgs_missing_matches[(rna_wgs_missing_matches['expected'] == 1) & (rna_wgs_missing_matches['observed'] == 0)]
rna_wgs_missing_matches.to_csv('multiomics/GECOPD/rna_wgs_missing_matches.csv')
rna_wgs_missing_matches

,Unnamed: 0,ID1,ID2,attempted,expected,observed,Concord
184,184,S-001566141_TCCGGAGA-AGGCGAAG_L006_accepted_hi...,NWD377956,1,1,0,NaN
210,210,S-001486013_ATTACTCG-TAATCTTA_L001_accepted_hi...,NWD680185,1,1,0,NaN
328,328,S-001551869_GAGATTCC-CCTATCCT_L003_accepted_hi...,NWD852265,1,1,0,NaN
394,394,S-001546829_ATTACTCG-AGGCGAAG_L005_accepted_hi...,NWD383350,1,1,0,NaN
466,466,S-001565706_TCCGCGAA-CCTATCCT_L006_accepted_hi...,NWD164029,1,1,0,NaN
...,...,...,...,...,...,...,...
157050,157050,S-001612561_TCCGGAGA-CCTATCCT_L002_accepted_hi...,NWD729844,1,1,0,NaN
157225,157225,S-001613620_TCTCGCGC-CCTATCCT_L003_accepted_hi...,NWD946987,1,1,0,NaN
157696,157696,S-001615226_accepted_hits.sorted.bam,NWD170815,1,1,0,NaN
157790,157790,S-001630862_accepted_hits.sorted.bam,NWD567978,1,1,0,NaN
157818,157818,S-001636291_accepted_hits.sorted.bam,NWD727640,1,1,0,NaN

In [53]:
BLOOD_MASTERFILE = '/proj/regeps/regep00/studies/COPDGene/data/rna/mrna/blood_shortread/TOPMED/data/TOPMED_11.19.2019/freezes/freeze1/masterfile/COPDGENE_TOPMED_blood_masterfile_6.7.21.tsv'
NASAL_MASTERFILE = '/proj/regeps/regep00/studies/COPDGene/data/rna/mrna/nasal_shortread/data/freezes/freeze1/masterfile/COPDGENE_TOPMED_nasal_masterfile_6.7.21.tsv'

blood_masterfile = pd.read_csv(BLOOD_MASTERFILE, delimiter='\t')
blood_masterfile

,Sample,sid,Subject Aliasid,Inv_plate,In_Ref,final_analyzed,geno_match,Y,PAR2,sid_orig,...,Mean 3' bias,Median 3' bias,3' bias Std,3' bias MAD_Std,"3' Bias, 25th Percentile","3' Bias, 75th Percentile",Median of Avg Transcript Coverage,Median of Transcript Coverage Std,Median of Transcript Coverage CV,Median Exon CV
0,301811,11320D,NJC11320D,Plate_1,1,yes,yes,1920,0,11320D,...,0.458201,0.432432,0.294495,0.358019,0.205128,0.696517,0,0,0.952649,0.236153
1,301813,20346W,BWH20346W,Plate_1,1,yes,yes,1047,0,20346W,...,0.460131,0.433333,0.294964,0.358295,0.209302,0.700000,0,0,0.993587,0.250469
2,301815,21558Q,BWH21558Q,Plate_1,1,yes,yes,1650,0,21558Q,...,0.456034,0.429752,0.285233,0.330658,0.226807,0.675325,0,0,0.882183,0.220347
3,301817,20193X,NJC20193X,Plate_1,1,yes,yes,1329,0,20193X,...,0.413209,0.363636,0.288385,0.315937,0.173913,0.620690,0,0,0.991603,0.264583
4,301819,20265W,NJC20265W,Plate_1,1,yes,yes,2393,0,20265W,...,0.401322,0.352332,0.279401,0.305881,0.168831,0.600000,0,0,0.848001,0.204834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,308234,30139X,BRCON2033,Plate_9,0,yes,no,67730,0,ON2033,...,0.455519,0.428571,0.288666,0.345326,0.214286,0.681818,0,0,0.822746,0.198720
382,308236,14582W,BRCAS1020,Plate_9,0,yes,yes,33119,0,AS1020,...,0.478601,0.457143,0.291632,0.356530,0.234584,0.715686,0,0,0.816485,0.186534
383,308238,25026D,BRCON2040,Plate_9,0,yes,yes,96263,0,ON2040,...,0.442940,0.405405,0.287319,0.340597,0.200000,0.666667,0,0,0.841323,0.180035
384,308240,30147W,BRCON2041,Plate_9,0,yes,no,123014,0,ON2041,...,0.418270,0.375000,0.285123,0.329296,0.178571,0.627451,0,0,0.784905,0.176148
385,308242,11769X,BRCAS1023,Plate_9,0,yes,yes,69886,0,AS1023,...,0.451357,0.421053,0.290219,0.350359,0.205128,0.684211,0,0,0.824144,0.187586

In [54]:
nasal_masterfile = pd.read_csv(NASAL_MASTERFILE, delimiter='\t')
nasal_masterfile

,Sample,sid,In_Ref,Inv_plate,final_analyzed,geno_match,gender_match,Y,Xist,sid_orig,...,Median 3' bias,3' bias Std,3' bias MAD_Std,"3' Bias, 25th Percentile","3' Bias, 75th Percentile",Median of Avg Transcript Coverage,Median of Transcript Coverage Std,Median of Transcript Coverage CV,Median Exon CV,Exon CV MAD
0,301810,11320D,1,Plate_1,yes,yes,yes,15889,8093,11320D,...,0.404255,0.292250,0.352444,0.187500,0.670588,0,0,0.854024,0.183331,0.174081
1,301812,20346W,1,Plate_1,yes,yes,yes,10933,12934,20346W,...,0.393939,0.288708,0.336955,0.183099,0.642857,0,0,0.835768,0.176039,0.166291
2,301814,21558Q,1,Plate_1,yes,yes,yes,14662,8926,21558Q,...,0.482759,0.295582,0.369156,0.222628,0.718750,0,0,0.924709,0.210105,0.199020
3,301816,20193X,1,Plate_1,yes,yes,yes,7438,11751,20193X,...,0.378788,0.290410,0.341946,0.161290,0.628571,0,0,0.877494,0.182848,0.176461
4,301818,20265W,1,Plate_1,yes,yes,yes,10388,13567,20265W,...,0.393600,0.293727,0.355459,0.173913,0.662162,0,0,0.864807,0.188717,0.179139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,308229,30132J,0,Plate_9,yes,no,yes,90245,42,ON2031,...,0.466667,0.290502,0.357601,0.238589,0.720930,0,0,0.776628,0.162731,0.155273
375,308231,17242N,0,Plate_9,yes,no,yes,64307,36,ON2032,...,0.523256,0.293824,0.367431,0.272727,0.767442,0,0,0.835926,0.187416,0.180015
376,308233,30139X,0,Plate_9,yes,no,yes,101144,47,ON2033,...,0.520913,0.294038,0.372003,0.265060,0.766667,0,0,0.836157,0.182396,0.179542
377,308235,14582W,0,Plate_9,yes,yes,yes,129387,115,AS1020,...,0.449275,0.293305,0.361452,0.217391,0.709677,0,0,0.793909,0.168469,0.162886
378,308239,30147W,0,Plate_9,yes,no,yes,77133,8,ON2041,...,0.442857,0.291555,0.359505,0.216216,0.703704,0,0,0.839963,0.186016,0.180366

In [56]:
combined_masterfile = pd.concat([blood_masterfile, nasal_masterfile])
combined_masterfile

,Sample,sid,Subject Aliasid,Inv_plate,In_Ref,final_analyzed,geno_match,Y,PAR2,sid_orig,...,3' bias MAD_Std,"3' Bias, 25th Percentile","3' Bias, 75th Percentile",Median of Avg Transcript Coverage,Median of Transcript Coverage Std,Median of Transcript Coverage CV,Median Exon CV,gender_match,Xist,Exon CV MAD
0,301811,11320D,NJC11320D,Plate_1,1,yes,yes,1920,0.0,11320D,...,0.358019,0.205128,0.696517,0,0,0.952649,0.236153,NaN,NaN,NaN
1,301813,20346W,BWH20346W,Plate_1,1,yes,yes,1047,0.0,20346W,...,0.358295,0.209302,0.700000,0,0,0.993587,0.250469,NaN,NaN,NaN
2,301815,21558Q,BWH21558Q,Plate_1,1,yes,yes,1650,0.0,21558Q,...,0.330658,0.226807,0.675325,0,0,0.882183,0.220347,NaN,NaN,NaN
3,301817,20193X,NJC20193X,Plate_1,1,yes,yes,1329,0.0,20193X,...,0.315937,0.173913,0.620690,0,0,0.991603,0.264583,NaN,NaN,NaN
4,301819,20265W,NJC20265W,Plate_1,1,yes,yes,2393,0.0,20265W,...,0.305881,0.168831,0.600000,0,0,0.848001,0.204834,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,308229,30132J,NaN,Plate_9,0,yes,no,90245,NaN,ON2031,...,0.357601,0.238589,0.720930,0,0,0.776628,0.162731,yes,42.0,0.155273
375,308231,17242N,NaN,Plate_9,0,yes,no,64307,NaN,ON2032,...,0.367431,0.272727,0.767442,0,0,0.835926,0.187416,yes,36.0,0.180015
376,308233,30139X,NaN,Plate_9,0,yes,no,101144,NaN,ON2033,...,0.372003,0.265060,0.766667,0,0,0.836157,0.182396,yes,47.0,0.179542
377,308235,14582W,NaN,Plate_9,0,yes,yes,129387,NaN,AS1020,...,0.361452,0.217391,0.709677,0,0,0.793909,0.168469,yes,115.0,0.162886
378,308239,30147W,NaN,Plate_9,0,yes,no,77133,NaN,ON2041,...,0.359505,0.216216,0.703704,0,0,0.839963,0.186016,yes,8.0,0.180366

In [33]:

rna_missing_nwds = rna_wgs_missing_matches['ID2'].to_frame()
wgs_non_rna_issues = wgs_samples.merge(rna_missing_nwds, left_on='SampleAlias', right_on='ID2', how='outer', indicator=True)
wgs_non_rna_issues = wgs_non_rna_issues[wgs_non_rna_issues['_merge'] == 'left_only']
wgs_non_rna_issues = wgs_non_rna_issues[wgs_non_rna_issues['flags'].notna()]
wgs_non_rna_issues.to_csv('multiomics/GECOPD/wgs_sample_issues.csv')
wgs_non_rna_issues['flags'].value_counts()

;cross_subject_match;unexpected_geno_nomatch                                 73
;cross_subject_match                                                         65
;unexpected_geno_nomatch                                                     62
cross_subject_match;gender_mismatch;unexpected_geno_nomatch                  38
observed_gender_indeterminate                                                17
gender_mismatch                                                              16
expected_gender_unknown                                                       9
cross_subject_match;observed_gender_indeterminate;unexpected_geno_nomatch     3
gender_mismatch;unexpected_geno_nomatch                                       2
cross_subject_match;gender_mismatch                                           2
Name: flags, dtype: int64

In [38]:
methylation_samples = multiomics[multiomics['dataset_id'] == 2]
methylation_samples['flags'].value_counts()

;cross_subject_match;unexpected_geno_nomatch                   200
;cross_subject_match                                           103
;unexpected_geno_nomatch                                        94
gender_mismatch;unexpected_geno_nomatch                          8
gender_mismatch                                                  6
cross_subject_match;gender_mismatch;unexpected_geno_nomatch      4
Name: flags, dtype: int64

In [47]:
flagged_methylation_samples = methylation_samples[methylation_samples['flags'].notna()]
flagged_methylation_samples.sort_values(['group_id'], inplace=True)
flagged_methylation_samples.to_csv('multiomics/GECOPD/flagged_methylation_samples.csv')
flagged_methylation_samples

/udd/rejpz/.conda/envs/cdnm-jupyter-python-3.7.6/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
26704,26704,26704,TOE171917_203693970018_R03C01_346336,S-001116430,TOE171917,m,2,0,ST-00007435,S-001116430,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32955,32955,32955,TOE256562_203712390022_R03C01_346365,S-001756529,TOE256562,m,2,0,ST-00007435,S-001756529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30462,30462,30462,TOE132699_203867050074_R01C01_363995,S-001734910,TOE132699,m,2,0,ST-00039640,S-001734910,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26765,26765,26765,TOE559878_203867050074_R02C01_363996,S-000562036,TOE559878,m,2,0,ST-00039640,S-000562036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25849,25849,25849,TOE291844_203497730199_R02C01_341513,S-001801744,TOE291844,m,2,0,ST-00007449,S-001801744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28571,28571,28571,TOE713898_203674650094_R06C01_342317,S-001773649,TOE713898,m,2,0,ST-01007794,S-001773649,...,NaN,NaN,reassign,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31013,31013,31013,TOE605797_203674650094_R05C01_342316,S-001559359,TOE605797,m,2,0,ST-01007794,S-001559359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24242,24242,24242,TOE949699_203674650099_R02C01_342329,S-001561222,TOE949699,m,2,0,ST-01007811,S-001561222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29195,29195,29195,TOE619053_203674650111_R04C01_342365,S-001787941,TOE619053,m,2,0,ST-01007811,S-001787941,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30163,30163,30163,TOE621195_204296550086_R06C01_381772,S-001750638,TOE621195,m,2,0,ST-01007859,S-001750638,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
flagged_methylation_samples.groupby('group_id').agg(list)

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,status,action_overridden.1,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat
group_id,,,,,,,,,,,,,,,,,,,,,
36,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
50,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
76,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
115,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
213,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8811,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
8841,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
8983,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
9810,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
10206,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3

In [44]:


flagged_rna_samples = multiomics[(multiomics['dataset_id'] == 3) | (multiomics['dataset_id'] == 4)]
rna_missing_sids = rna_wgs_missing_matches['ID1'].to_frame()
flagged_rna_samples = flagged_rna_samples[flagged_rna_samples['flags'].notna()]
flagged_rna_samples = flagged_rna_samples.merge(rna_missing_sids, left_on='SampleAlias', right_on='ID1', how='outer', indicator=True)
flagged_rna_samples = flagged_rna_samples[flagged_rna_samples['_merge'] == 'left_only']
flagged_rna_samples.to_csv('multiomics/GECOPD/flagged_rna_samples.csv')
flagged_rna_samples['flags'].value_counts()

observed_gender_missing                        183
;cross_subject_match                            15
cross_subject_match;gender_mismatch             13
;unexpected_geno_nomatch                         8
gender_mismatch                                  6
cross_subject_match;observed_gender_missing      1
Name: flags, dtype: int64

In [51]:
flagged_rna_samples.groupby('group_id').agg(len)

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,action,IID_x,F,IID_y,F_MISS,IID,SNPSEX,XHomFStat,ID1,_merge
group_id,,,,,,,,,,,,,,,,,,,,,
411,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
412,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
733,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
923,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1045,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10681,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
10686,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
10687,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
10691,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
10693,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [46]:
flagged_unified_samples = multiomics[multiomics['dataset_id'] == 1]
flagged_unified_samples = flagged_unified_samples[flagged_unified_samples['flags'].notna()]
flagged_unified_samples.to_csv('multiomics/GECOPD/flagged_unified_samples.csv')
flagged_unified_samples['flags'].value_counts()

observed_gender_missing                                                101
;cross_subject_match;unexpected_geno_nomatch                            83
;cross_subject_match                                                    50
;unexpected_geno_nomatch                                                41
observed_gender_indeterminate                                            6
observed_gender_missing;unexpected_geno_nomatch                          4
cross_subject_match;observed_gender_missing;unexpected_geno_nomatch      2
gender_mismatch                                                          2
cross_subject_match;observed_gender_missing                              1
Name: flags, dtype: int64

multiomics