In [1]:
import pandas as pd
import os

WORKDIR = '/proj/regeps/regep00/studies/TopMed/data/dna/whole_genome/TopMed/data/freezes/freeze.10.cdnm'
os.chdir(WORKDIR)

In [2]:
MASTERFILE = '/proj/edith/regeps/regep00/studies/COPDGene/data/rnaseq/BLOOD/archivalroot/Masterfile/master.file.freeze4.txt'
masterfile = pd.read_csv(MASTERFILE, sep='\t')
masterfile

,sample_id,sample,COPDgeneID,actual_id,BAM_file,in_star_report,in_metrics,in_pearson,in_spearman,in_sample_sex,...,pass_pearson_corr,pass_kinship,user_keep,process,notes,final.analyzed,batch,BAM_id,RNA_id,Lc.Batch
0,S-001177272,S-001177272_TCCGCGAA-GTACTGAC_L005,10866Q,10934H,S-001177272_TCCGCGAA-GTACTGAC_L005_accepted_hi...,True,True,True,True,True,...,True,False,True,link,NaN,1,batch_13_170209_7001411_0478_BC9TG3ANXX,10934H_batch_13_170209_7001411_0478_BC9TG3ANXX...,10934H_batch_13_170209_7001411_0478_BC9TG3ANXX,7780150303-4
1,S-001177736,S-001177736_AGCGATAG-GTACTGAC_L008,20729M,20729M,S-001177736_AGCGATAG-GTACTGAC_L008_accepted_hi...,True,True,True,True,True,...,True,True,True,link,NaN,1,batch_49_180828_7001411_0771_BCCFY9ANXX,20729M_batch_49_180828_7001411_0771_BCCFY9ANXX...,20729M_batch_49_180828_7001411_0771_BCCFY9ANXX,12762376589_4
2,S-001178531,S-001178531_TCTCGCGC-TATAGCCT_L006,15730Q,11620P,S-001178531_TCTCGCGC-TATAGCCT_L006_accepted_hi...,True,True,True,True,True,...,True,False,True,link,NaN,1,batch_13_170209_7001411_0478_BC9TG3ANXX,11620P_batch_13_170209_7001411_0478_BC9TG3ANXX...,11620P_batch_13_170209_7001411_0478_BC9TG3ANXX,7780150303-4
3,S-001178538,S-001178538_ATTACTCG-AGGCGAAG_L004,11126H,11126H,S-001178538_ATTACTCG-AGGCGAAG_L004_accepted_hi...,True,True,True,True,True,...,True,True,True,link,NaN,1,161004_7001411_0434,11126H_161004_7001411_0434.bam,11126H_161004_7001411_0434,6093890587-3
4,S-001178548,S-001178548_TCTCGCGC-ATAGAGGC_L006,15039G,12534B,S-001178548_TCTCGCGC-ATAGAGGC_L006_accepted_hi...,True,True,True,True,True,...,True,False,True,link,NaN,1,batch_13_170209_7001411_0478_BC9TG3ANXX,12534B_batch_13_170209_7001411_0478_BC9TG3ANXX...,12534B_batch_13_170209_7001411_0478_BC9TG3ANXX,7780150303-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,S-001648320,S-001648320_CCAAGTCT-AAGGATGA_L002,19433E,19433E,S-001648320_CCAAGTCT-AAGGATGA_L002_accepted_hi...,True,True,True,True,True,...,True,False,True,drop,failed.kinship,0,batch_79_190920_7001411_0894_ACDMJNANXX,19433E_batch_79_190920_7001411_0894_ACDMJNANXX...,19433E_batch_79_190920_7001411_0894_ACDMJNANXX,NaN
4800,S-001648321,S-001648321_TGGATCGA-GTGCGATA_L001,24728E,24728E,S-001648321_TGGATCGA-GTGCGATA_L001_accepted_hi...,True,True,True,True,True,...,True,False,True,drop,failed.kinship,0,batch_79_190920_7001411_0894_ACDMJNANXX,24728E_batch_79_190920_7001411_0894_ACDMJNANXX...,24728E_batch_79_190920_7001411_0894_ACDMJNANXX,NaN
4801,S-001648322,S-001648322_GGACTTGG-CGCAGACG_L001,23798U,23798U,S-001648322_GGACTTGG-CGCAGACG_L001_accepted_hi...,True,True,True,True,True,...,True,False,True,drop,failed.kinship,0,batch_79_190920_7001411_0894_ACDMJNANXX,23798U_batch_79_190920_7001411_0894_ACDMJNANXX...,23798U_batch_79_190920_7001411_0894_ACDMJNANXX,NaN
4802,S-001648323,S-001648323_TTGGACTC-GGAAGCAG_L002,25389N,25389N,S-001648323_TTGGACTC-GGAAGCAG_L002_accepted_hi...,True,True,True,True,True,...,True,False,True,drop,failed.kinship,0,batch_79_190920_7001411_0894_ACDMJNANXX,25389N_batch_79_190920_7001411_0894_ACDMJNANXX...,25389N_batch_79_190920_7001411_0894_ACDMJNANXX,NaN
4803,S-001648324,S-001648324_CTCTCGTC-TATAACCT_L002,26132H,26132H,S-001648324_CTCTCGTC-TATAACCT_L002_accepted_hi...,True,True,True,True,True,...,True,True,True,link,NaN,1,batch_79_190920_7001411_0894_ACDMJNANXX,26132H_batch_79_190920_7001411_0894_ACDMJNANXX...,26132H_batch_79_190920_7001411_0894_ACDMJNANXX,21173020180-3

In [34]:
reassignments = masterfile[masterfile['COPDgeneID'] != masterfile['actual_id']]
reassignments = reassignments[reassignments['final.analyzed'] == 1]
reassignments = reassignments[['sample_id', 'COPDgeneID', 'actual_id']]
reassignments

        sample_id COPDgeneID actual_id
0     S-001177272     10866Q    10934H
2     S-001178531     15730Q    11620P
4     S-001178548     15039G    12534B
5     S-001178707     21146T    18332T
7     S-001486012     10137H    16425Q
...           ...        ...       ...
1622  S-001570711     12534B    10525Q
1624  S-001570713     18332T    20628G
1834  S-001577061     17319W    17157W
2683  S-001596687     24270J    24335L
3321  S-001607745     26040C    26136P

[82 rows x 3 columns]

In [26]:
ALIASES = '/proj/regeps/regep00/studies/COPDGene/metadata/topmed_aliases.txt'
aliases = pd.read_csv(ALIASES)
aliases = aliases[aliases['ALIASTYPE'] == 'Pheno Id']
aliases = aliases.drop_duplicates()
aliases

        S_SAMPLEID  S_SUBJECTID S_STUDYID ALIASTYPE ALIASID
0      S-001121917  ST-00007812    GECOPD  Pheno Id  11775S
2      S-001117816  ST-00008184    GECOPD  Pheno Id  13672S
4      S-001117529  ST-00032762    GECOPD  Pheno Id  12163S
6      S-001117825  ST-00007969    GECOPD  Pheno Id  12565M
8      S-001116627  ST-00007612    GECOPD  Pheno Id  10780G
...            ...          ...       ...       ...     ...
21974  S-001592641  ST-01001797    GECOPD  Pheno Id  22261Y
21976  S-001627434  ST-01001423    GECOPD  Pheno Id  23327H
21978  S-001603919  ST-01001811    GECOPD  Pheno Id  23150U
21980  S-001627561  ST-00030561    GECOPD  Pheno Id  21398U
21982  S-001566519  ST-01002525    GECOPD  Pheno Id  24002K

[10844 rows x 5 columns]

In [38]:
reassignments = reassignments.merge(aliases, left_on='COPDgeneID', right_on='ALIASID', how='left')
reassignments = reassignments.merge(aliases, left_on='actual_id', right_on='ALIASID', how='left')
reassignments = reassignments[['sample_id', 'COPDgeneID', 'actual_id', 'S_SUBJECTID_x', 'S_SUBJECTID_y']]
reassignments = reassignments.rename(columns={'S_SUBJECTID_x': 'reassign_from', 'S_SUBJECTID_y': 'reassign_to'})
reassignments.drop_duplicates(inplace=True)
reassignments.to_csv(f'{WORKDIR}/freeze10qc_rna_reassignments.csv', index=False)
reassignments

      sample_id COPDgeneID actual_id reassign_from  reassign_to
0   S-001177272     10866Q    10934H   ST-00076410  ST-00075699
1   S-001178531     15730Q    11620P   ST-00034432  ST-00075284
2   S-001178548     15039G    12534B   ST-00078794  ST-00077841
3   S-001178707     21146T    18332T   ST-00032869  ST-00036759
4   S-001486012     10137H    16425Q   ST-00075665  ST-00075027
..          ...        ...       ...           ...          ...
87  S-001570711     12534B    10525Q   ST-00077841  ST-00074132
88  S-001570713     18332T    20628G   ST-00036759  ST-00077425
89  S-001577061     17319W    17157W   ST-00074846  ST-00074841
90  S-001596687     24270J    24335L   ST-01000560  ST-01002546
91  S-001607745     26040C    26136P   ST-01007859  ST-01007811

[82 rows x 5 columns]