In [1]:
import os
import pandas as pd
from pathlib import Path

In [15]:

FREEZE10 = '/proj/regeps/regep00/studies/TopMed/data/dna/whole_genome/TopMed/data/freezes/freeze.10.cdnm/'
MANIFEST_E = 'multiomics/EOCOPD/ANNOTATED_MANIFEST.csv'
MANIFEST_I = 'multiomics/GLAXO/ANNOTATED_MANIFEST.csv'
MANIFEST_P = 'multiomics/PLCOPD/ANNOTATED_MANIFEST.csv'

In [5]:
os.chdir(FREEZE10)

----

# EOCOPD

In [12]:
manifest = pd.read_csv(MANIFEST_E)
manifest

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,u_collectiontypid,u_legacyfamilyid,u_packageid,ExpectedGender,ObservedGender,flags,group_id,c_group,action,status
0,0,0,NWD100047,NaN,NWD100047,w,0,0,ST-00040454,S-000614256,...,NaN,NaN,NaN,F,F,NaN,724,0,keep,NaN
1,1,1,NWD100794,NaN,NWD100794,w,0,0,ST-00038746,S-000607373,...,NaN,NaN,NaN,F,F,NaN,640,1,keep,NaN
2,2,2,NWD102671,NaN,NWD102671,w,0,0,ST-00035100,S-000292488,...,NaN,NaN,NaN,F,F,NaN,355,2,keep,NaN
3,3,3,NWD106037,NaN,NWD106037,w,0,0,ST-00063906,S-001161680,...,NaN,NaN,NaN,F,F,NaN,1112,3,keep,NaN
4,4,4,NWD106415,NaN,NWD106415,w,0,0,ST-00037184,S-000626726,...,NaN,NaN,NaN,F,F,NaN,532,4,keep,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,2230,2230,ax:ST-01006044,NaN,ax:ST-01006044,d,2,0,ST-01006044,NaN,...,NaN,NaN,NaN,M,M,NaN,1163,893,keep,NaN
2231,2231,2231,ax:ST-01013321,NaN,ax:ST-01013321,d,2,0,ST-01013321,NaN,...,NaN,NaN,NaN,F,F,NaN,1189,2231,keep,NaN
2232,2232,2232,ax:ST-01013322,NaN,ax:ST-01013322,d,2,0,ST-01013322,NaN,...,NaN,NaN,NaN,F,F,NaN,1190,2232,keep,NaN
2233,2233,2233,ax:ST-01015833,NaN,ax:ST-01015833,d,2,0,ST-01015833,NaN,...,NaN,NaN,NaN,M,M,NaN,1191,81,keep,NaN
2234,2234,2234,ax:ST-01026292,NaN,ax:ST-01026292,d,2,0,ST-01026292,NaN,...,NaN,NaN,NaN,F,F,NaN,1193,68,keep,NaN

----

# ICGN/GLAXO

In [16]:
manifest_i = pd.read_csv(MANIFEST_I)
manifest_i

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,u_collectiontypid,u_legacyfamilyid,u_packageid,ExpectedGender,ObservedGender,flags,group_id,c_group,action,status
0,0,0,NWD102259,NaN,NWD102259,w,0,0,ST-00015107,S-000448307,...,NaN,NaN,NaN,F,F,NaN,479,0,keep,NaN
1,1,1,NWD105171,NaN,NWD105171,w,0,0,ST-00015254,S-000447567,...,NaN,NaN,NaN,F,F,NaN,622,1,keep,NaN
2,2,2,NWD105332,NaN,NWD105332,w,0,0,ST-00015159,S-000446821,...,NaN,NaN,NaN,F,F,NaN,529,2,keep,NaN
3,3,3,NWD106110,NaN,NWD106110,w,0,0,ST-00023771,S-000448099,...,NaN,NaN,NaN,M,M,NaN,2086,3,keep,NaN
4,4,4,NWD107349,NaN,NWD107349,w,0,0,ST-00023240,S-000447284,...,NaN,NaN,NaN,M,M,NaN,1562,4,keep,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5866,5866,5866,ST-00024593,NaN,ST-00024593,x,2,0,ST-00024593,NaN,...,NaN,NaN,NaN,M,M,NaN,2891,2688,keep,NaN
5867,5867,5867,ST-00015896,NaN,ST-00015896,x,2,0,ST-00015896,NaN,...,NaN,NaN,NaN,F,F,NaN,1253,2687,keep,NaN
5868,5868,5868,ST-00015923,NaN,ST-00015923,x,2,0,ST-00015923,NaN,...,NaN,NaN,NaN,F,F,NaN,1280,2698,keep,NaN
5869,5869,5869,ST-00024706,NaN,ST-00024706,x,2,0,ST-00024706,NaN,...,NaN,NaN,NaN,M,M,NaN,3003,2692,keep,NaN
5870,5870,5870,ST-00024602,NaN,ST-00024602,x,2,0,ST-00024602,NaN,...,NaN,NaN,NaN,M,M,NaN,2900,5870,keep,NaN

----

# PLCOPD

In [14]:
manifest_p = pd.read_csv(MANIFEST_P)
manifest_p

,Unnamed: 0,Unnamed: 0.1,SampleLabel,S_SAMPLEID_manifest,SampleAlias,SampleTypeCode,dataset_id,is_reference,S_SUBJECTID,S_SAMPLEID,...,u_collectiontypid,u_legacyfamilyid,u_packageid,ExpectedGender,ObservedGender,flags,group_id,c_group,action,status
0,0,0,NWD106403,NaN,NWD106403,w,0,0,ST-00079924,S-000969548,...,NaN,NaN,NaN,F,F,NaN,639,0,keep,NaN
1,1,1,NWD108770,NaN,NWD108770,w,0,0,ST-00030551,S-000524828,...,NaN,NaN,NaN,M,M,NaN,15,1,keep,NaN
2,2,2,NWD118909,NaN,NWD118909,w,0,0,ST-00029841,S-000508791,...,NaN,NaN,NaN,M,M,NaN,4,2,keep,NaN
3,3,3,NWD120989,NaN,NWD120989,w,0,0,ST-00035152,S-000566969,...,NaN,NaN,NaN,M,M,NaN,219,3,keep,NaN
4,4,4,NWD127225,NaN,NWD127225,w,0,0,ST-00033274,S-000586961,...,NaN,NaN,NaN,M,M,NaN,102,4,keep,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,1489,1489,ax:ST-00079992,NaN,ST-00079992,d,2,0,ST-00079992,NaN,...,NaN,NaN,NaN,M,M,NaN,650,838,keep,NaN
1490,1490,1490,ax:ST-00079993,NaN,ST-00079993,d,2,0,ST-00079993,NaN,...,NaN,NaN,NaN,M,M,NaN,651,111,keep,NaN
1491,1491,1491,ax:ST-00079994,NaN,ST-00079994,d,2,0,ST-00079994,NaN,...,NaN,NaN,NaN,M,M,NaN,652,264,keep,NaN
1492,1492,1492,ax:ST-00079995,NaN,ST-00079995,d,2,0,ST-00079995,NaN,...,NaN,NaN,NaN,M,M,NaN,653,108,keep,NaN
1493,1493,1493,ax:ST-00080113,NaN,ST-00080113,d,2,0,ST-00080113,NaN,...,NaN,NaN,NaN,F,F,NaN,654,181,keep,NaN